preload = ['./preload.js'] # Application 시작 전 실행할 스크립트
# smol = true # 성능을 희생하면서 메모리 사용량을 줄임
# logLevel = "error" # 로그 레벨을 설정 debug warn error
telemetry = false # 분석 기록을 활성/비활성화. 

[define]
test = "testValue"